## ==========================================
## 00_phase0_setup.R
## Phase 0 - Project root + folder structure + project brief
## ==========================================

# ریشه‌ی پروژه (مسیر ثابت برای این کار)
project_root <- "D:/Research/My Articles/DLBCL drug"

# 1) ساخت ریشه و زیرپوشه‌ها
dir.create(project_root, recursive = TRUE, showWarnings = FALSE)

subdirs <- c(
  "data/raw",
  "data/processed",
  "metadata",
  "results/figures",
  "results/tables",
  "scripts",
  "docs",
  "logs"
)

invisible(
  sapply(file.path(project_root, subdirs), dir.create,
         recursive = TRUE, showWarnings = FALSE)
)

# 2) مسیر فایل project brief
brief_path <- file.path(project_root, "docs", "00_project_brief_DLBCL.md")

# 3) محتوای project brief (فاز صفر)
brief_lines <- c(
  "# DLBCL Cross-species Disease Module & Drug Repurposing Project",
  "",
  "## Project Root",
  paste0("- Path: `", project_root, "`"),
  "",
  "## 1. Disease definition – Human (DLBCL)",
  "",
  "- **Disease:** Adult de novo diffuse large B-cell lymphoma (DLBCL).",
  "- **In-scope:**",
  "  - Tumor samples from lymph node / lymphoid tissues labelled as DLBCL.",
  "  - Adult patients treated mainly with R-CHOP or R-CHOP-like regimens.",
  "  - Cohorts with at least one of:",
  "    - Overall survival (OS) / progression-free survival (PFS).",
  "    - Response categories (CR/PR vs SD/PD, or responder vs non-responder).",
  "    - Tumor vs normal samples (tonsil / lymph node).",
  "- **Out-of-scope (Human):**",
  "  - Primary CNS DLBCL.",
  "  - Primary mediastinal B-cell lymphoma (PMBCL), unless explicitly merged as DLBCL.",
  "  - Primary testicular DLBCL (unless explicitly included later by design).",
  "  - Pediatric / young DLBCL (focus is adults).",
  "- **Data types (Human): bulk transcriptome**",
  "  - Microarray (gene-level).",
  "  - RNA-seq (counts / TPM) from tumor ± normal.",
  "",
  "## 2. Disease definition – Dog (Canine DLBCL)",
  "",
  "- **Disease:** Canine multicentric high-grade B-cell lymphoma (DLBCL-like).",
  "- **In-scope (Dog):**",
  "  - Biopsy / aspirate from lymph node / spleen reported as B-cell lymphoma / DLBCL.",
  "  - Pre-treatment (baseline) samples, ideally before CHOP / CHOP-like therapy.",
  "  - Cohorts with:",
  "    - DLBCL vs healthy lymph node.",
  "    - And/or PFS / OS / response to CHOP.",
  "- **Out-of-scope (Dog):**",
  "  - T-cell lymphoma.",
  "  - Low-grade / indolent lymphoma.",
  "  - Poorly annotated “lymphoma NOS” with no clear B-cell typing.",
  "- **Data types (Dog): bulk transcriptome**",
  "  - Microarray (gene-level).",
  "  - RNA-seq (counts / TPM).",
  "",
  "## 3. Core Questions (Operational Form)",
  "",
  "### Q1 – What is the shared human–dog DLBCL gene module?",
  "",
  "- **Operational definition:**",
  "  - A set of human–dog ortholog genes that:",
  "    - Are significantly dysregulated in human DLBCL vs normal.",
  "    - Are associated with outcome (survival / response) in human cohorts.",
  "    - Show similar dysregulation (same direction) in canine DLBCL vs normal.",
  "    - And, if outcome data exist in dog, associate with PFS / response.",
  "",
  "### Q2 – Is this module associated with outcome/response?",
  "",
  "- For each human cohort (e.g., GSE10846, TCGA DLBCL):",
  "  - **X:** module score per sample (e.g., GSVA score / WGCNA eigengene).",
  "  - **Y:** outcome:",
  "    - Survival time + status (Cox model).",
  "    - Or binary response (responder vs non-responder).",
  "- Hypothesis:",
  "  - Higher or lower module score is associated with worse/better outcome.",
  "  - (The expected direction will be confirmed empirically, but we assume *disease module* corresponds to more aggressive biology.)",
  "- For dog:",
  "  - **X:** same module score.",
  "  - **Y:** PFS / response to CHOP, when available.",
  "",
  "### Q3 – Which drugs can revert this module towards a healthy-like state in both species?",
  "",
  "- Define a **disease signature** based on the cross-species module:",
  "  - Up-disease genes: up-regulated in tumor vs normal.",
  "  - Down-disease genes: down-regulated in tumor vs normal.",
  "- Desired drug effect:",
  "  - In CMap/LINCS (or similar), the drug signature:",
  "    - Down-regulates up-disease genes.",
  "    - Up-regulates down-disease genes.",
  "- A **good candidate drug**:",
  "  - Shows a strong negative connectivity score vs disease signature.",
  "  - Preferentially tested in B-cell / lymphoma cell lines.",
  "  - Has reasonable translatability / feasibility in both humans and dogs.",
  "",
  "## 4. Data Levels (mRNA / miRNA / EV)",
  "",
  "### Core level (minimum viable project)",
  "",
  "- Human bulk mRNA:",
  "  - ≥ 2 cohorts with outcome (survival / response).",
  "- Canine bulk mRNA:",
  "  - ≥ 1 DLBCL cohort (ideally with PFS / response).",
  "- Outputs:",
  "  - Cross-species disease module.",
  "  - Drug repurposing based on mRNA signature only.",
  "",
  "### Level-up 1 – miRNA (optional but valuable)",
  "",
  "- Conditions to activate this level:",
  "  - At least one human DLBCL miRNA cohort with:",
  "    - Tumor vs normal, or responder vs non-responder.",
  "  - AND at least one canine lymphoma miRNA dataset (tumor vs normal or serum/EV-miRNA).",
  "- Workflow idea:",
  "  - Differential miRNA analysis (DEmiR).",
  "  - miRNA targets from miRTarBase / TargetScan / miRDB.",
  "  - Restrict targets to genes in the cross-species disease module.",
  "  - Build a miRNA–module regulatory network.",
  "- Rule:",
  "  - If these conditions are **not** met, main paper remains purely mRNA-based and miRNA is declared as future / exploratory work.",
  "",
  "### Level-up 2 – EV (highly optional / opportunistic)",
  "",
  "- EV-miRNA / EV-mRNA datasets in human / canine DLBCL.",
  "- If **no** reasonable EV datasets exist, the project still proceeds as mRNA ± miRNA.",
  "",
  "### Final statement:",
  "",
  "- **Minimum publishable version:** mRNA-based cross-species disease module + drug repurposing.",
  "- **Advanced version:** same, plus a miRNA layer (and EV if feasible).",
  "",
  "## 5. Dataset Inclusion / Exclusion Criteria",
  "",
  "### Human – Inclusion criteria",
  "",
  "- Disease: DLBCL (or DLBCL-dominant cohorts where subtypes can be filtered).",
  "- Data type:",
  "  - Microarray (gene-level expression matrix).",
  "  - RNA-seq (counts or normalized expression).",
  "- Sample type:",
  "  - Tumor biopsy / lymph node tissue.",
  "- Clinical / experimental data:",
  "  - At least one of:",
  "    - OS / PFS with status.",
  "    - Response to R-CHOP / R-CHOP-like (CR/PR vs SD/PD or similar).",
  "    - Tumor vs normal samples.",
  "- Sample size (guideline):",
  "  - Preferably n ≥ 50 for discovery cohorts with outcome.",
  "  - Smaller cohorts can be used for validation only.",
  "",
  "### Human – Exclusion criteria",
  "",
  "- Pure cell line datasets (unless used separately in a cell-line-specific phase).",
  "- Datasets with very poor clinical annotation.",
  "- Expression data that cannot be robustly mapped to gene symbols.",
  "",
  "### Dog – Inclusion criteria",
  "",
  "- Disease: canine B-cell lymphoma / DLBCL, clearly annotated.",
  "- Data type:",
  "  - Microarray (gene-level).",
  "  - RNA-seq (counts / normalized).",
  "- Sample type:",
  "  - Tumor lymph node / spleen ± healthy lymph node.",
  "- Clinical data (ideal, but we accept weaker datasets due to rarity):",
  "  - DLBCL vs healthy lymph node.",
  "  - PFS / OS / response to CHOP where available.",
  "- Sample size (guideline):",
  "  - Ideally n ≥ 15–20 DLBCL cases.",
  "",
  "### Dog – Exclusion criteria",
  "",
  "- T-cell lymphomas.",
  "- Low-grade / indolent lymphomas.",
  "- Heterogeneous “lymphoma NOS” with no clear B-cell typing, unless justified later.",
  "",
  "## 6. Planned Outputs",
  "",
  "### Main manuscript",
  "",
  "- **Working title (draft):**",
  "  - “Cross-species disease modules and drug repurposing in human and canine diffuse large B-cell lymphoma”",
  "- **Target journals (initial ideas, to be refined later):**",
  "  - A high-quality comparative / translational oncology journal (Q1).",
  "  - A backup option in genomics / translational medicine (e.g., BMC Genomics, Genomic Medicine, Cancers, etc.).",
  "",
  "### Technical outputs",
  "",
  "- Final list of genes in the cross-species disease module (for Supplementary tables).",
  "- Module score per sample for all cohorts (CSV files).",
  "- Shortlist of drug candidates with:",
  "  - CMap/LINCS connectivity scores.",
  "  - Target genes / pathways.",
  "  - Status (approved / experimental) and feasibility in humans and dogs.",
  "",
  "## 7. Planned Figures (high-level sketch)",
  "",
  "- **Figure 1:** Overall project design + dataset selection overview.",
  "- **Figure 2:** Human DLBCL co-expression modules + association with outcome.",
  "- **Figure 3:** Projection of the human module onto dog data and definition of the cross-species core module.",
  "- **Figure 4 (optional):** miRNA / EV regulatory layer on top of the module.",
  "- **Figure 5:** PPI network of the cross-species module + hubs / submodules.",
  "- **Figure 6:** Drug repurposing hits + schematic translation to human & dog.",
  "",
  "---",
  "",
  "_This file was auto-generated as Phase 0 (definition & scope) bootstrap via 00_phase0_setup.R._"
)

writeLines(brief_lines, brief_path, useBytes = TRUE)

cat("\n[Phase 0] Project structure + project brief created.\n")
cat("Root: ", project_root, "\n", sep = "")
cat("Brief file: ", brief_path, "\n\n", sep = "")
